### PR TITLE
Add newlib sqrtf

### PR DESCRIPTION
**Pull request by lzutao**
I ported sqrtf from https://github.com/eblot/newlib/blob/master/newlib/libm/math/ef_sqrt.c .

r? @japaric 

Blocked on #173

### CODE REVIEW

**Comment by lzutao** [comment]
cc #170

**Comment by alexcrichton** [comment]
Thanks for the PR! I have the same questions as https://github.com/rust-lang-nursery/libm/pull/169 for this though. Why is this change being made relative to what's currently already implemented?

**Comment by alexcrichton** [comment]
Is this just a reorganization of what's already there at this point? If so, why is this PR needed?

**Comment by lzutao** [comment]
Seems like we don't agree the merge this. Closing then.

**Pull request closed without merging**
